name: optimize-molecule
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask
  - flask-cors
  - numpy
  - scipy
  - matplotlib
  - ase
  - qiskit
  - pip
  - python-dotenv
  - stripe
  - pip:
      - dill
      - qiskit-aer
      - qiskit-algorithms
      - gunicorn
      - flask-sqlalchemy

