# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - molcompute

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Create and activate a virtual environment
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install dependencies (including ase and flask-cors)
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          pip install ase flask-cors

      # Optional: Run tests (add if you have tests)
      # - name: Run tests
      #   run: |
      #     source venv/bin/activate
      #     pytest

      # Package the application for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" "*.zip"

      # Upload the packaged app as an artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      # Download the artifact created during the build step
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Unzip the artifact
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Log in to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DB05AE43E3DF428C8B13F12B83A08A65 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_743A1AE0B0484302A297E0C4C0B6DA8B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E9255A3763D943E49D6F6B96B383C4D8 }}

      # Deploy the app to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'molcompute'
          slot-name: 'Production'
